### PR TITLE
fix: #7 JWK thumbprint includes optional members when calculated

### LINKED ISSUE #7: [Bug]: JWK thumbprint includes optional members when calculated
### Contact Details

_No response_

### Describe the bug

When a DPoP is parsed, the JWK thumbprint should only include required members when calculated. See https://datatracker.ietf.org/doc/html/rfc7638#section-3.2

Related lines of code:
https://github.com/AxisCommunications/go-dpop/blob/e3feea2490d9593bff6ca6a73dd5548219e2f3aa/parse.go#L124-L137

### Steps to reproduce the behavior

Create a proof with a JWK containing optional fields, for example:

```
{
  "crv": "P-256",
  "ext": true,
  "kty": "EC",
  "x": "KDVM3aXrYGUgmKyo0q__DdIDVS0AV139ZTba04SKqFQ",
  "y": "SC-oR4qLdhmwrjr6PjJ7_LfFpC_BSFUT14LnMtgjHPs"
}
```

In this example, "ext" should be excluded.

### OS

_No response_

### Relevant log output

_No response_

### Additional Notes

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by a354dpa**
### Describe your changes

Extracted functionality to parse a JWK to a function. Use that to extract a "minimal" JWK (the JWK without optional or custom fields) to do the JWK fingerprinting with 

### Issue ticket number and link

- Fixes #7 

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: parse.go [hunk 1]
```diff
@@ -240,3 +249,52 @@ func base64urlTrailingPadding(s string) ([]byte, error) {
...
+		return nil, err
+	}
+	return jwkHeaderJSONBytes, nil
+}
+
+// Returns the string representation of a key in JSON format.
+func getKeyStringRepresentation(key interface{}) ([]byte, error) {
+	var keyParts interface{}
+	switch key.(type) {
+	case *ecdsa.PublicKey:
```
Comment (SalladinBalwer) [inline parse.go:271]: You can assign key in the case which removes the need to type cast inside the case. 
```suggestion
	case key = *ecdsa.PublicKey:
```

Comment (a354dpa) [reply parse.go:271]: Done. Did not know that. Was very elegant

**Comment by SalladinBalwer** [comment]
Please change the title of the PR from `feat: ...` to `fix: ...` to get the correct SemVer.

**Review by SalladinBalwer — APPROVED** [review]
